# Generated by Django 4.2.24 on 2025-12-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrefernces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=100, unique=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_histories', to='events.events')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_histories', to='templates.templates')),
            ],
        ),
    ]
